### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by elie222** [fcFn/frontend-test-1#1]
Don't change the DOM directly:
https://github.com/fcFn/frontend-test-1/blob/master/src/components/card/index.js#L63

Use .map() for lists:
https://github.com/fcFn/frontend-test-1/blob/master/src/components/card-list/index.js#L9

For lists see here: https://reactjs.org/docs/lists-and-keys.html

**Comment by fcFn** [comment]
Thanks a ton! That's more feedback than I got from the company. Made a few enhancements along the way, too!
